name: ${project.name}
main: vg.civcraft.mc.civchat2.CivChat2
version: ${project.version}
author: jjj5311
depend: [NameLayer, CivModCore]
softdepend: [Mercury, BetterShards]
description: CivChat2 limits the chat radius to 1000 blocks. However Private Messaging and Group Chat works above the 1000 block chat radius.
commands:
    tell:
      aliases: [message, msg, m, pm, t, whisper, w]
    afk:
    reply:
      aliases: [r]
    ignore:
      aliases: [i]
    ignoregroup:
      aliases: [ig, igroup, ignoreg]
    groupc:
      aliases: [groupchat, gchat, gc, g, chat]
    ignorelist:
    exit:
      aliases: [e]
    mute:
      permission: civchat2.mute
permissions:
    CivChat2.*:
      description: Gives access to /sayall
      default: op
      children:
        - civchat2.mute
